pool:
  name: Azure Pipelines
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- script: 'pip install mkdocs'
  displayName: 'Install MKDocs'

- script: 'mkdocs build'
  displayName: 'Build MKDocs'

- script: |
   git config --global user.name "kevmcdonk"
   git config --global user.email "kevin@mcd79.com"
   mkdir gh-pages
   echo 'List root directory'
   dir
   cd gh-pages
   echo 'List gh-pages directory'
   dir
   git clone --single-branch --branch gh-pages https://77517c7317093e6efb5bc074907dd9784f52aee5@github.com/GreyHatBeard/m365-etiquette
   echo 'List gh-pages after pull'
   dir
   cd ..
   echo 'List root directory'
   dir
   cp -R site/* gh-pages/m365-etiquette
   cd gh-pages/m365-etiquette
   echo 'List gh-pages after copy'
   dir
   git add --all
   git commit --message 'Adding and updating files'
   git push
   dir
  displayName: 'Command Line Script'

- script: 'mkdocs gh-deploy'
  displayName: 'Deploy MKDocs'
  enabled: false

