site_name: Etiquette of Microsoft 365
nav:
  - Home: '/m365-etiquette'
  - By Service:
    - 'Outlook': '/By-service/outlook'
  - About:
    - 'What is etiquette of Microsoft 365 about?': 'about'
theme:
  name: 'mkdocs'
  palette:
    primary: 'orange'
  logo: 'images/GreyHatBeard-large.png'
  feature:
    tabs: true
google_analytics:
  - 'UA-159089413-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/greyhatbeard'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCCbalP0tGZ1kyD1A0GQeVDQ'
    - type: 'link'
      link: 'https://www.greyhatbeard.com'
repo_url: https://github.com/GreyHatBeard/m365-etiquette
edit_uri: blob/gh-docs
