site_name: Etiquette of Microsoft 365
nav:
  - Home: 'index.md'
  - By Service:
    - 'Summary': 'By-service/readme.md'
    - 'Outlook': 'By-service/Outlook'
    - 'Teams': 'By-service/Teams'
    - 'OneNote': 'By-service/OneNote'
    - 'Planner': 'By-service/Planner'
  - By Approach:
    - 'Summary': 'By-approach/readme.md'
    - 'Asking questions': 'By-approach/Asking-questions'
    - 'Communicating': 'By-approach/Communicating'
    - 'Files': 'By-approach/Files'
    - 'Liking posts': 'By-approach/Liking-posts'
    - 'Voice': 'By-approach/Voice'
    - 'Working Out Loud': 'By-approach/Working-out-loud'
  - By scenario:
    - 'Summary': 'By-scenario/readme.md'
  - About:
    - 'What is etiquette of Microsoft 365 about?': 'about.md'
theme:
  name: 'material'
  palette:
    primary: 'deep orange'
  logo: '/m365-etiquette/images/GreyHatBeardAvatars-wide.png'
  feature:
    tabs: true
google_analytics:
  - 'UA-159089413-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/greyhatbeard
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/greyhatbeard
    - icon: fontawesome/solid/link
      link: https://www.greyhatbeard.com
repo_url: https://github.com/GreyHatBeard/m365-etiquette
edit_uri: edit/master/docs
