site_name: Etiquette of Microsoft 365
nav:
  - Home: '/m365-etiquette'
  - By Service:
    - 'Outlook': 'By-service/outlook'
    - 'Teams': 'By-service/teams'
    - 'OneNote': 'By-service/onenote'
    - 'Planner': 'By-service/planner'
  - By Approach:
    - Communicating: '/m365-etiquette/By-approach/communicating'
    - Files: '/m365-etiquette/By-approach/files'
    - Voice: '/m365-etiquette/By-approach/voice'
  - About:
    - 'What is etiquette of Microsoft 365 about?': 'about'
theme:
  name: 'material'
  palette:
    primary: 'orange'
  logo: '/m365-etiquette/images/GreyHatBeard-large.png'
  feature:
    tabs: true
google_analytics:
  - 'UA-159089413-1'
  - 'auto'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  social:
    - type: 'twitter'
      link: 'https://twitter.com/greyhatbeard'
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCCbalP0tGZ1kyD1A0GQeVDQ'
    - type: 'link'
      link: 'https://www.greyhatbeard.com'
repo_url: https://github.com/GreyHatBeard/m365-etiquette
edit_uri: blob/gh-docs
